export type IphoneModelSpec = {
  name: string;
  year: number;
  capacities: string[];
  colors: { name: string; hex: string }[];
};

export const IPHONE_CATALOG: IphoneModelSpec[] = [
  {
    name: "iPhone 17 Pro Max",
    year: 2025,
    capacities: ["256GB", "512GB", "1TB", "2TB"],
    colors: [
      { name: "Prateado", hex: "#e2e4e1" },
      { name: "Laranja-cósmico", hex: "#e65c00" },
      { name: "Azul-intenso", hex: "#1d3557" },
    ],
  },
  {
    name: "iPhone 17 Pro",
    year: 2025,
    capacities: ["256GB", "512GB", "1TB"],
    colors: [
      { name: "Prateado", hex: "#e2e4e1" },
      { name: "Laranja-cósmico", hex: "#e65c00" },
      { name: "Azul-intenso", hex: "#1d3557" },
    ],
  },
  {
    name: "iPhone 17",
    year: 2025,
    capacities: ["256GB", "512GB"],
    colors: [
      { name: "Preto", hex: "#1d1d1f" },
      { name: "Branco", hex: "#f7f7f7" },
      { name: "Azul-névoa", hex: "#a7c1d9" },
      { name: "Sálvia", hex: "#778e78" },
      { name: "Lavanda", hex: "#b5a7cb" },
    ],
  },
  {
    name: "iPhone Air",
    year: 2025,
    capacities: ["256GB", "512GB", "1TB"],
    colors: [
      { name: "Preto-espacial", hex: "#2e2c2e" },
      { name: "Branco-nuvem", hex: "#f2f1ed" },
      { name: "Dourado-claro", hex: "#fae7cf" },
      { name: "Azul-céu", hex: "#87ceeb" },
    ],
  },
  {
    name: "iPhone 17e",
    year: 2026,
    capacities: ["256GB", "512GB"],
    colors: [
      { name: "Preto", hex: "#1d1d1f" },
      { name: "Branco", hex: "#f7f7f7" },
      { name: "Rosa-pálido", hex: "#faddd7" },
    ],
  },
  {
    name: "iPhone 16 Pro Max",
    year: 2024,
    capacities: ["256GB", "512GB", "1TB"],
    colors: [
      { name: "Titânio-deserto", hex: "#c6aa91" },
      { name: "Titânio natural", hex: "#bebaa7" },
      { name: "Titânio branco", hex: "#f2f1ed" },
      { name: "Titânio preto", hex: "#3c3b37" },
    ],
  },
  {
    name: "iPhone 16 Pro",
    year: 2024,
    capacities: ["128GB", "256GB", "512GB", "1TB"],
    colors: [
      { name: "Titânio-deserto", hex: "#c6aa91" },
      { name: "Titânio natural", hex: "#bebaa7" },
      { name: "Titânio branco", hex: "#f2f1ed" },
      { name: "Titânio preto", hex: "#3c3b37" },
    ],
  },
  {
    name: "iPhone 16 Plus",
    year: 2024,
    capacities: ["128GB", "256GB", "512GB"],
    colors: [
      { name: "Preto", hex: "#1d1d1f" },
      { name: "Branco", hex: "#f7f7f7" },
      { name: "Rosa", hex: "#faddd7" },
      { name: "Verde-acinzentado", hex: "#8ab4ac" },
      { name: "Ultramarino", hex: "#42506e" },
    ],
  },
  {
    name: "iPhone 16",
    year: 2024,
    capacities: ["128GB", "256GB", "512GB"],
    colors: [
      { name: "Preto", hex: "#1d1d1f" },
      { name: "Branco", hex: "#f7f7f7" },
      { name: "Rosa", hex: "#faddd7" },
      { name: "Verde-acinzentado", hex: "#8ab4ac" },
      { name: "Ultramarino", hex: "#42506e" },
    ],
  },
  {
    name: "iPhone 16e",
    year: 2025,
    capacities: ["128GB", "256GB", "512GB"],
    colors: [
      { name: "Preto", hex: "#1d1d1f" },
      { name: "Branco", hex: "#f7f7f7" },
    ],
  },
  {
    name: "iPhone 15 Pro Max",
    year: 2023,
    capacities: ["256GB", "512GB", "1TB"],
    colors: [
      { name: "Titânio natural", hex: "#bebaa7" },
      { name: "Titânio azul", hex: "#3b4453" },
      { name: "Titânio branco", hex: "#f2f1ed" },
      { name: "Titânio preto", hex: "#3c3b37" },
    ],
  },
  {
    name: "iPhone 15 Pro",
    year: 2023,
    capacities: ["128GB", "256GB", "512GB", "1TB"],
    colors: [
      { name: "Titânio natural", hex: "#bebaa7" },
      { name: "Titânio azul", hex: "#3b4453" },
      { name: "Titânio branco", hex: "#f2f1ed" },
      { name: "Titânio preto", hex: "#3c3b37" },
    ],
  },
  {
    name: "iPhone 15 Plus",
    year: 2023,
    capacities: ["128GB", "256GB", "512GB"],
    colors: [
      { name: "Preto", hex: "#1d1d1f" },
      { name: "Azul", hex: "#a7c1d9" },
      { name: "Verde", hex: "#b4caa4" },
      { name: "Amarelo", hex: "#f3e08c" },
      { name: "Rosa", hex: "#faddd7" },
    ],
  },
  {
    name: "iPhone 15",
    year: 2023,
    capacities: ["128GB", "256GB", "512GB"],
    colors: [
      { name: "Preto", hex: "#1d1d1f" },
      { name: "Azul", hex: "#a7c1d9" },
      { name: "Verde", hex: "#b4caa4" },
      { name: "Amarelo", hex: "#f3e08c" },
      { name: "Rosa", hex: "#faddd7" },
    ],
  },
  {
    name: "iPhone 14 Pro Max",
    year: 2022,
    capacities: ["128GB", "256GB", "512GB", "1TB"],
    colors: [
      { name: "Roxo-profundo", hex: "#483d8b" },
      { name: "Preto-espacial", hex: "#2e2c2e" },
      { name: "Dourado", hex: "#fae7cf" },
      { name: "Prateado", hex: "#e2e4e1" },
    ],
  },
  {
    name: "iPhone 14 Pro",
    year: 2022,
    capacities: ["128GB", "256GB", "512GB", "1TB"],
    colors: [
      { name: "Roxo-profundo", hex: "#483d8b" },
      { name: "Preto-espacial", hex: "#2e2c2e" },
      { name: "Dourado", hex: "#fae7cf" },
      { name: "Prateado", hex: "#e2e4e1" },
    ],
  },
  {
    name: "iPhone 14 Plus",
    year: 2022,
    capacities: ["128GB", "256GB", "512GB"],
    colors: [
      { name: "Meia-noite", hex: "#1b242d" },
      { name: "Estelar", hex: "#f0e9d7" },
      { name: "(PRODUCT)RED", hex: "#e30016" },
      { name: "Azul", hex: "#a7c1d9" },
      { name: "Roxo", hex: "#b5a7cb" },
      { name: "Amarelo", hex: "#f3e08c" },
    ],
  },
  {
    name: "iPhone 14",
    year: 2022,
    capacities: ["128GB", "256GB", "512GB"],
    colors: [
      { name: "Meia-noite", hex: "#1b242d" },
      { name: "Estelar", hex: "#f0e9d7" },
      { name: "(PRODUCT)RED", hex: "#e30016" },
      { name: "Azul", hex: "#a7c1d9" },
      { name: "Roxo", hex: "#b5a7cb" },
      { name: "Amarelo", hex: "#f3e08c" },
    ],
  },
  {
    name: "iPhone SE (3ª geração)",
    year: 2022,
    capacities: ["64GB", "128GB", "256GB"],
    colors: [
      { name: "Meia-noite", hex: "#1b242d" },
      { name: "Estelar", hex: "#f0e9d7" },
      { name: "(PRODUCT)RED", hex: "#e30016" },
    ],
  },
  {
    name: "iPhone 13 Pro Max",
    year: 2021,
    capacities: ["128GB", "256GB", "512GB", "1TB"],
    colors: [
      { name: "Azul-Sierra", hex: "#9bb0c1" },
      { name: "Verde-alpino", hex: "#475c4d" },
      { name: "Grafite", hex: "#545351" },
      { name: "Dourado", hex: "#fae7cf" },
      { name: "Prateado", hex: "#e2e4e1" },
    ],
  },
  {
    name: "iPhone 13 Pro",
    year: 2021,
    capacities: ["128GB", "256GB", "512GB", "1TB"],
    colors: [
      { name: "Azul-Sierra", hex: "#9bb0c1" },
      { name: "Verde-alpino", hex: "#475c4d" },
      { name: "Grafite", hex: "#545351" },
      { name: "Dourado", hex: "#fae7cf" },
      { name: "Prateado", hex: "#e2e4e1" },
    ],
  },
  {
    name: "iPhone 13",
    year: 2021,
    capacities: ["128GB", "256GB", "512GB"],
    colors: [
      { name: "Meia-noite", hex: "#1b242d" },
      { name: "Estelar", hex: "#f0e9d7" },
      { name: "Azul", hex: "#42506e" },
      { name: "Rosa", hex: "#faddd7" },
      { name: "Verde", hex: "#475c4d" },
      { name: "(PRODUCT)RED", hex: "#e30016" },
    ],
  },
  {
    name: "iPhone 13 mini",
    year: 2021,
    capacities: ["128GB", "256GB", "512GB"],
    colors: [
      { name: "Meia-noite", hex: "#1b242d" },
      { name: "Estelar", hex: "#f0e9d7" },
      { name: "Azul", hex: "#42506e" },
      { name: "Rosa", hex: "#faddd7" },
      { name: "Verde", hex: "#475c4d" },
      { name: "(PRODUCT)RED", hex: "#e30016" },
    ],
  },
  {
    name: "iPhone 12 Pro Max",
    year: 2020,
    capacities: ["128GB", "256GB", "512GB"],
    colors: [
      { name: "Azul-Pacífico", hex: "#2c4d5e" },
      { name: "Grafite", hex: "#545351" },
      { name: "Dourado", hex: "#fae7cf" },
      { name: "Prateado", hex: "#e2e4e1" },
    ],
  },
  {
    name: "iPhone 12 Pro",
    year: 2020,
    capacities: ["128GB", "256GB", "512GB"],
    colors: [
      { name: "Azul-Pacífico", hex: "#2c4d5e" },
      { name: "Grafite", hex: "#545351" },
      { name: "Dourado", hex: "#fae7cf" },
      { name: "Prateado", hex: "#e2e4e1" },
    ],
  },
  {
    name: "iPhone 12",
    year: 2020,
    capacities: ["64GB", "128GB", "256GB"],
    colors: [
      { name: "Preto", hex: "#1d1d1f" },
      { name: "Branco", hex: "#f7f7f7" },
      { name: "Azul", hex: "#1d3557" },
      { name: "Verde", hex: "#b4caa4" },
      { name: "Roxo", hex: "#b5a7cb" },
      { name: "(PRODUCT)RED", hex: "#e30016" },
    ],
  },
  {
    name: "iPhone 12 mini",
    year: 2020,
    capacities: ["64GB", "128GB", "256GB"],
    colors: [
      { name: "Preto", hex: "#1d1d1f" },
      { name: "Branco", hex: "#f7f7f7" },
      { name: "Azul", hex: "#1d3557" },
      { name: "Verde", hex: "#b4caa4" },
      { name: "Roxo", hex: "#b5a7cb" },
      { name: "(PRODUCT)RED", hex: "#e30016" },
    ],
  },
  {
    name: "iPhone 11 Pro Max",
    year: 2019,
    capacities: ["64GB", "256GB", "512GB"],
    colors: [
      { name: "Verde meia-noite", hex: "#4e5851" },
      { name: "Cinza-espacial", hex: "#4b4a4e" },
      { name: "Dourado", hex: "#fae7cf" },
      { name: "Prateado", hex: "#e2e4e1" },
    ],
  },
  {
    name: "iPhone 11 Pro",
    year: 2019,
    capacities: ["64GB", "256GB", "512GB"],
    colors: [
      { name: "Verde meia-noite", hex: "#4e5851" },
      { name: "Cinza-espacial", hex: "#4b4a4e" },
      { name: "Dourado", hex: "#fae7cf" },
      { name: "Prateado", hex: "#e2e4e1" },
    ],
  },
  {
    name: "iPhone 11",
    year: 2019,
    capacities: ["64GB", "128GB", "256GB"],
    colors: [
      { name: "Preto", hex: "#1d1d1f" },
      { name: "Branco", hex: "#f7f7f7" },
      { name: "Roxo", hex: "#d1c4e9" },
      { name: "Verde", hex: "#b2dfdb" },
      { name: "Amarelo", hex: "#fff59d" },
      { name: "(PRODUCT)RED", hex: "#e30016" },
    ],
  },
  {
    name: "iPhone XR",
    year: 2018,
    capacities: ["64GB", "128GB", "256GB"],
    colors: [
      { name: "Preto", hex: "#1d1d1f" },
      { name: "Branco", hex: "#f7f7f7" },
      { name: "Azul", hex: "#42a5f5" },
      { name: "Amarelo", hex: "#ffee58" },
      { name: "Coral", hex: "#ff7043" },
      { name: "(PRODUCT)RED", hex: "#e30016" },
    ],
  },
];
